### ISSUE TITLE
Make TOC work

### ISSUE THREAD

**Issue by ghost** [Montapacking/AzureDevOpsWikiToDocFx#3]
Azure DevOps gives the option to insert a table of content. Then "[[_TOC_]]" is inserted in Markdown. This is not rendered in the HTML page.

**Comment by ghost** [comment]
DocFX shows the TOC already in the right column of a page. So the pipeline task should just remove "[[_TOC_]]" from the page.

**Comment by jvdslikke** [comment]
Done, [[TOC]] is now removed from the page
