### ISSUE TITLE
Minimal Example

### ISSUE THREAD

**Issue by NKlinke** [Montapacking/AzureDevOpsWikiToDocFx#7]
Hi there, 

I really favor the idea of this pipeline. Nevertheless, having no experience with docfx, I have trouble running the pipeline without errors. 
May I ask for a minimal example as part of the Repo?

My current setup looks like this: 
![image](https://user-images.githubusercontent.com/17301532/166195031-55577d69-380e-48ad-99c3-6cca9b24a3a4.png)

I added .oder and .attachments after getting error messages that were complaining about those files being missing. The latest error message was requesting a toc.yml, which I added then. No the error declares that the yml isn't valid. I attached the log file with this message. Please advice how to solve this issue.
[azure_log.txt](https://github.com/Montapacking/AzureDevOpsWikiToDocFx/files/8601244/azure_log.txt)

Best Regards

**Comment by ghost** [comment]
Dear NKlinke,

If you create a wiki in Azure Devops, it automatically creates the right file structure for you. See: https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-create-repo?view=azure-devops

The toc.yml should be created by the AzureDevOpsWikiToDocFx task. Then the DocFx task can run. E.g. with an azure-pipelines.yml file like below. 


![image](https://user-images.githubusercontent.com/46046319/183756392-9bac83bf-4de6-41f7-b77b-38eb3afcdb22.png)

**Comment by NKlinke** [comment]
Dear jvdsmonta,

no matter if I include the toc.yml or if it is not present in the repo, the pipeline fails at the exact same action and reports that "D:\a\1\s\docfx\test\toc.yml is not a valid TOC File"

My pipeline looks exactly like in your screenshot. 

Please help me debugging this. 

Best regards
